config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用
  devise_for :member, skip: [:passwords] ,controllers: {
    registrations: "member/registrations",
    sessions: 'member/sessions'
  }

  # ゲストログイン
  devise_scope :member do
    post 'member/guest_sign_in', to: 'member/sessions#guest_sign_in'
  end

  root 'homes#top'

  get '/about', to: 'homes#about'

  #チーム開発カリキュラム詳細設計
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
  end

  scope module: :member do
    get "search" => "searches#search"
    resources :videos, only: [:index, :new, :show, :create, :destroy] do
      resource :nices, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      collection do
        get 'users/unsubscribe'
        patch 'users/withdraw'
      end
      member do
      get :nices
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    redirect_to user_path(current_member.id) if member_signed_in?
    redirect_to admin_genres_path if admin_signed_in?
  end

  def about
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-10 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg px-0 my-5">
        <h5 class="text-dark bg-secondary py-4 mb-0 sabu-name">about</h5>
        <div class="form-body bg-light p-4">
          <div class="mx-auto text-left">
            <p>
              今回私がこのPFのテーマを選んだ理由は、２点あります。<br>
              ①プログラミング初心者の自分が3ヶ月で学んできたことを最大限活かす<br>
              ②ラグビーを幼少期からしており、練習動画などを管理、すぐに見返すことのできるよう解決する。<br>
              <br>
              この２つを取り入れることで少しでも、自分なりのPFができると考え作成致しました。<br>
              作成を進めるにあたり、動画容量での動きの遅さ、PF自体のスマートさがまだまだ学習が必要だと感じる反面<br>
              3ヶ月の成長を実感できました。<br>
              人生で初めてのPFで、至らずところが多々ありますが最後まで楽しく考えながら作成する事ができました。<br>

              日々成長できるよう、今後も頑張りたいと思います。
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/homes/top.html.erb
<%= notice %>
  <div class="first-view top-title">
    <div class="first-view-text">
      <h1>Welcome to My sports record!!</h1>
      <p>〜自分のスポーツを保存しよう〜</p>
      <div class="link-button-area">
        <%= link_to "Log-in", new_member_session_path, class: "btn btn-outline-secondary btn-lg px-4" %>
        <%= link_to "Sign-up", new_member_registration_path, class: "btn btn-outline-secondary btn-lg px-4" %>
        <%= link_to 'ゲストログイン（閲覧用）', member_guest_sign_in_path, class: "btn btn-outline-secondary btn-lg px-4", method: :post %>
      </div>
    </div>
  </div>