config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用
  devise_for :member, skip: [:passwords] ,controllers: {
    registrations: "member/registrations",
    sessions: 'member/sessions'
  }

  # ゲストログイン
  devise_scope :member do
    post 'member/guest_sign_in', to: 'member/sessions#guest_sign_in'
  end

  root 'homes#top'

  get '/about', to: 'homes#about'

  #チーム開発カリキュラム詳細設計
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
  end

  scope module: :member do
    get "search" => "searches#search"
    resources :videos, only: [:index, :new, :show, :create, :destroy] do
      resource :nices, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      collection do
        get 'users/unsubscribe'
        patch 'users/withdraw'
      end
      member do
      get :nices
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #アプリケーションを完成させよう2 14章
  has_one_attached :video
  has_one_attached :image
  #コメント機能
  has_many :comments, dependent: :destroy
  #いいね機能
  has_many :nices, dependent: :destroy

  def get_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  #検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @member = Member.where("last_name LIKE?", "#{word}")
    elsif search == "forward_match"
      @member = Member.where("last_name LIKE?","#{word}%")
    elsif search == "backward_match"
      @member = Member.where("last_name LIKE?","%#{word}")
    elsif search == "partial_match"
      @member = Member.where("last_name LIKE?","%#{word}%")
    else
      @member = Member.all
    end
  end

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(last_name: 'ゲスト' ,email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
      member.last_name = "ゲスト"
      member.first_name = "太郎"
      member.last_name_kana = "ゲスト"
      member.first_name_kana = "タロウ"
      member.email = "guest@example.com"

    end
  end

end

app/controllers/member/comments_controller.rb
class Member::CommentsController < ApplicationController
  def create
    video = Video.find(params[:video_id])
    comment = current_member.comments.new(comment_params)
    comment.video_id = video.id
    comment.save
    redirect_to video_path(video.id)
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to video_path(params[:video_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/member/confirmations_controller.rb
# frozen_string_literal: true

class Member::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/member/nices_controller.rb
class Member::NicesController < ApplicationController

  def create
    @video = Video.find(params[:video_id])
    nice = current_member.nices.new(video_id: @video.id)
    nice.save
    #redirect_to video_path(video.id)
  end

  def destroy
    @video = Video.find(params[:video_id])
    nice = current_member.nices.find_by(video_id: @video.id)
    nice.destroy
    #redirect_to video_path(video.id)
  end

end

app/controllers/member/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Member::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/member/passwords_controller.rb
# frozen_string_literal: true

class Member::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/member/registrations_controller.rb
# frozen_string_literal: true

class Member::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_sign_up_path_for(resource)
    user_path(current_member)
  end


end

app/controllers/member/searches_controller.rb
class Member::SearchesController < ApplicationController
  before_action :authenticate_member!


  def search
    @range = params[:range]

    if @range == "Member"
      @members = Member.looks(params[:search], params[:word])
    else
      @videos = Video.looks(params[:search], params[:word]).order(id: "DESC").page(params[:page])#順番・ページネーション
    end
  end

end

app/controllers/member/sessions_controller.rb
# frozen_string_literal: true

class Member::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def guest_sign_in
    member = Member.guest
    sign_in member
    redirect_to user_path(current_member), notice: 'guest-memberでログインしました。'
  end

  protected

  def reject_member
    # 退会しているかを判断するメソッド
    @member = Member.find_by(name: params[:member])
    # 【処理内容1】 入力されたemailからアカウントを1件取得
    if @member
      if @member.valid_password?(params[:member][:password]) && (@member.id_deleted == false)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_member_registration
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end

end

app/controllers/member/unlocks_controller.rb
# frozen_string_literal: true

class Member::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/member/users_controller.rb
class Member::UsersController < ApplicationController
  before_action :ensure_guest_member, only: [:edit]

  def show
    @genres = Genre.all
    @member = Member.find(params[:id])
    @videos = Video.where(member_id: params[:id]).order(id: "DESC").page(params[:page]).per(6)#ページネーション
  end

  def edit
    @member = Member.find(params[:id])
    if current_member != @member
      redirect_to user_path(@member.id)
    end
  end

  def update
    @member = Member.find(params[:id])
    @member.update(member_params)
    redirect_to user_path(@member.id)
  end

  def unsubscribe
  end

  def withdraw
    @member = current_member
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @member.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  #いいね一覧
  def nices
    @member = Member.find(params[:id])
    nices= Nice.where(member_id: @member.id).pluck(:video_id)
    @nice_videos = Kaminari.paginate_array(Video.find(nices)).page(params[:page]).per(6) # FIXME: per
  end

  private

  def member_params
    params.require(:member).permit(:last_name, :first_name, :image)
  end

  #ゲストログイン機能
  def ensure_guest_member
    @member = Member.find(params[:id])
    if @member.last_name == "ゲスト"
      redirect_to root_path, notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end

end

app/controllers/member/videos_controller.rb
class Member::VideosController < ApplicationController
  def index
    @genres = Genre.all
    @videos = Video.order(id: "DESC").page(params[:page]).per(6)#順番・ページネーション
    if params[:genre_id] != nil
      @videos = Video.where(genre_id: params[:genre_id]).order(id: "DESC").page(params[:page]).per(6)#順番・ページネーション
    end
  end

  def new
    @video = Video.new
    @genres = Genre.all
  end

  def create
    @video = Video.new(video_params)
    @video.member_id = current_member.id
    if @video.save
      redirect_to user_path(current_member.id)
    else
      @genres = Genre.all
      render :new
    end
  end

  def show
    @genres = Genre.all
    @deleted_member_ids = Member.where(is_deleted: true).ids
    @video = Video.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to new_video_path
  end

  private

  def video_params
    params.require(:video).permit(:title, :explanation, :video, :image, :genre_id)
  end

end

app/helpers/member/comments_helper.rb
module Member::CommentsHelper
end

app/helpers/member/nices_helper.rb
module Member::NicesHelper
end

app/helpers/member/searches_helper.rb
module Member::SearchesHelper
end

app/helpers/member/users_helper.rb
module Member::UsersHelper
end

app/helpers/member/videos_helper.rb
module Member::VideosHelper
end

app/views/member/users/edit.html.erb
  <div class="container">
    <div class="row">
      <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center px-0 my-5">
        <h5 class="title-font text-dark p-4 mb-0">Profile editing</h5><!--背景色bg-light-->
          <div class="title-font form-body p-4">
          <%= form_with model: @member, url: user_path(current_member) do |f| %>
            <label for="inputImage">ProfileImage</label> <br>
            <!--プロフィール画像-->
            <%= f.file_field :image, placeholder: "プロフィール画像", accept: "image/*" %> <br>
          <div class="p-2">
            <label for="inputName">last_name</label> <br>
            <!--名字-->
            <%= f.text_field :last_name, autofocus: true, id:"inputName", placeholder:"姓"%> <br>
          </div>
          <div class="p-2">
            <label for="inputName">first_name</label> <br>
            <!--名前-->
            <%= f.text_field :first_name, autofocus: true, id:"inputName", placeholder:"名"%> <br>
          </div>
          <div class="p-2">
            <!--ボタン-->
            <%= f.submit "Save", class: 'btn btn-sm btn-success col-md-6' %>
          </div>
          <div class="p-2">
            <!--退会ボタン-->
            <%= link_to "Withdraw", users_unsubscribe_users_path, class: 'btn btn-sm btn-danger col-md-6' %>
          </div>

          <% end %>
          </div>
      </div>

app/views/member/users/nices.html.erb
<div class="back-color title-font">
  <h3 class="text-center">New</h3>
    <div class="album py-4">
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          <% @nice_videos.each do |video| %>
            <div class="col p-3">
              <div class="card shadow-sm">
                <% if video.image.attached? %>
                  <div class="samu" style="background-image: url(<%= rails_blob_path(video.image) %>)"></div>
                <% else %>
                  <div class="samu"></div>
                <% end %>
                <div class="card-body">
                  <p>
                    <% if video.member.image.attached? %>
                      <%= image_tag video.member.image, size: "60x60" %>
                    <% else %>
                      <%= image_tag 'no_image', size: "60x60" %>
                    <% end %>
                  </p>
                  <p class="card-title">Title:<%= link_to video.title, video_path(video.id) %></p>
                  <p class="card-text">Explanation：<%= video.explanation %></p>
                  <span><%= video.created_at.strftime('%Y/%m/%d') %></span>
                  <span>Number of comments：<%= video.comments.count %></span>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="p-5">
        <%= paginate @nice_videos %>
      </div>
    </div>
</div>

app/views/member/users/show.html.erb
<!-- ユーザーの詳細 -->
<div class="profile-container border-bottom">
  <div class="w-75 d-flex mx-auto justify-content-around align-items-center py-5 name-name">
    <% if @member.image.attached? %>
      <%= image_tag @member.image, size: "100x100" %>
    <% else %>
      <%= image_tag 'no_image', size: "100x100" %>
    <% end %>
    <h3><%= @member.last_name %></h3>
    <h3><%= @member.first_name %></h3>
    <div class="mt-auto">
      <% if @member.first_name != "太郎" && @member.last_name != "ゲスト" %>
      <% if current_member == @member %>
      <p><%= link_to "Profile editing", edit_user_path(@member), class: 'btn btn-sm btn-success' %></p>
      <% end %>
      <% end %>
      <p><%=link_to"Nice story",nices_user_path(@member), class: 'btn btn-sm btn-success' %></p>
    </div>
  </div>
</div>

<!-- ユーザーの投稿動画一覧 -->
<div class="back-color title-font">
  <h3 class="text-center">MY MOVE</h3>
    <div class="album py-4">
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          <% @videos.each do |video| %>
            <div class="col p-3">
              <div class="card shadow-sm">
                <% if video.image.attached? %>
                  <div class="samu" style="background-image: url(<%= rails_blob_path(video.image) %>)"></div>
                <% else %>
                  <div class="samu"></div>
                <% end %>
                  <div class="card-body">
                    <p class="card-title">Title:<%= link_to video.title, video_path(video.id) %></p>
                    <p class="card-text">Explanation：<%= video.explanation %></p>
                    <span>
                      <i class="fa fa-calendar"></i>
                      <%= video.created_at.strftime('%Y/%m/%d') %>
                       ｜
                    </span>
                    <span>
                      <i class="fa fa-comment"></i>
                      <%= video.comments.count %>
                       ｜
                    </span>
                  </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="p-5">
      <%= paginate @videos %>
      </div>
    </div>
</div>

app/views/member/users/unsubscribe.html.erb
 <div class="container">
  <div class="row no-gutters">
   <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
    <h5 class="title-font text-dark bg-light p-4 mb-0">Be careful</h5>
     <div class="form-body p-4">
      退会手続きをされますと、全てのサービスがご利用いただけなくなります。<br>
      再度ご利用をいただく場合には、新規登録のお手続きが必要になります。<br>
      本当に退会してよろしいですか？
     </div>
     <div class="p-2">
      <%= link_to "Withdraw", users_withdraw_users_path, method: :patch, data: { confilm: "本当に退会しますか？" }, class: 'btn btn-sm btn-danger col-md-6' %>
     </div>
     <div class="p-2">
      <%= link_to "Do not", user_path(current_member), class: 'btn btn-sm btn-primary col-md-6' %>
     </div>
   </div>
  </div>
 </div>