config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用
  devise_for :member, skip: [:passwords] ,controllers: {
    registrations: "member/registrations",
    sessions: 'member/sessions'
  }

  # ゲストログイン
  devise_scope :member do
    post 'member/guest_sign_in', to: 'member/sessions#guest_sign_in'
  end

  root 'homes#top'

  get '/about', to: 'homes#about'

  #チーム開発カリキュラム詳細設計
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
  end

  scope module: :member do
    get "search" => "searches#search"
    resources :videos, only: [:index, :new, :show, :create, :destroy] do
      resource :nices, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      collection do
        get 'users/unsubscribe'
        patch 'users/withdraw'
      end
      member do
      get :nices
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :video
  
  
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :videos

  validates :genre_name, presence: true

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #アプリケーションを完成させよう2 14章
  has_one_attached :video
  has_one_attached :image
  #コメント機能
  has_many :comments, dependent: :destroy
  #いいね機能
  has_many :nices, dependent: :destroy

  def get_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  #検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @member = Member.where("last_name LIKE?", "#{word}")
    elsif search == "forward_match"
      @member = Member.where("last_name LIKE?","#{word}%")
    elsif search == "backward_match"
      @member = Member.where("last_name LIKE?","%#{word}")
    elsif search == "partial_match"
      @member = Member.where("last_name LIKE?","%#{word}%")
    else
      @member = Member.all
    end
  end

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(last_name: 'ゲスト' ,email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
      member.last_name = "ゲスト"
      member.first_name = "太郎"
      member.last_name_kana = "ゲスト"
      member.first_name_kana = "タロウ"
      member.email = "guest@example.com"

    end
  end

end

app/models/nice.rb
class Nice < ApplicationRecord


  belongs_to :member
  belongs_to :video

end

app/models/video.rb
class Video < ApplicationRecord
  has_one_attached :video
  has_one_attached :image

  belongs_to :member
  has_many :comments, dependent: :destroy
  belongs_to :genre
  has_many :nices, dependent: :destroy

  validates :title, presence: true
  validates :explanation, presence: true
  validates :video, presence: true
  #サイズバリデーション
  validate :size_validation
  #ビデオタイプバリデーション
  validate :video_type

  def niced_by?(member)
    nices.exists?(member_id: member.id)
  end

  # 検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @video = Video.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @video = Video.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @video = Video.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @video = Video.where("title LIKE?","%#{word}%")
    else
      @video = Video.all
    end
  end

  #サイズバリデーション
  def size_validation
    if video.present?
      errors.add(:video,'の容量が大きいです') if video.blob.byte_size > 200.megabytes#約２分
    end
  end

  #ビデオタイプバリデーション
  def video_type
    if video.blob.content_type != "video/mp4"
      errors.add(:videos, 'はmp4形式でアップロードしてください')
    end
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.page(params[:page]).per(5)
  end

  def create
    @genres = Genre.all
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to request.referer
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_member!, except: [:top, :about], unless: :admin_signed_in?
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_member)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name, :last_name, :first_name_kana, :last_name_kana])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    redirect_to user_path(current_member.id) if member_signed_in?
    redirect_to admin_genres_path if admin_signed_in?
  end

  def about
  end
end

app/controllers/member/nices_controller.rb
class Member::NicesController < ApplicationController

  def create
    @video = Video.find(params[:video_id])
    nice = current_member.nices.new(video_id: @video.id)
    nice.save
    #redirect_to video_path(video.id)
  end

  def destroy
    @video = Video.find(params[:video_id])
    nice = current_member.nices.find_by(video_id: @video.id)
    nice.destroy
    #redirect_to video_path(video.id)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/member/comments_helper.rb
module Member::CommentsHelper
end

app/helpers/member/nices_helper.rb
module Member::NicesHelper
end

app/helpers/member/searches_helper.rb
module Member::SearchesHelper
end

app/helpers/member/users_helper.rb
module Member::UsersHelper
end

app/helpers/member/videos_helper.rb
module Member::VideosHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My sports record!!</title>
    <!--スマートフォン用表示-->
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--stylesheetsをいじる際に記載する-->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--google fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap" rel="stylesheet">
  </head>

  <body>

    <header class="header">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand" href="/"><span class="header-logo shadow_White">My sports record!!</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto shadow_White">
              <%# ユーザーログイン後のヘッダー%>
              <% if member_signed_in? %>
                <li><%= link_to 'Home', videos_path, class: 'nav-link text-dark' %></li>
                <li><%= link_to 'My page', user_path(current_member.id), class: 'nav-link text-dark' %></li>
                <li><%= link_to 'Post form', new_video_path, class: 'nav-link text-dark' %></li>
                <li><%= link_to 'Log out', destroy_member_session_path, method: :delete, class: 'nav-link text-dark' %></li>
              <%# 管理者ログイン後のヘッダー　%>
              <% elsif admin_signed_in? %>
                <li><%= link_to 'Member list', admin_customers_path, class: 'nav-link text-dark' %></li>
                <li><%= link_to 'Genre list', admin_genres_path, class: 'nav-link text-dark' %></li>
                <li><%= link_to 'Log out', destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %></li>
              <%# ログイン前のヘッダー(ユーザー、管理者共通)　%>
              <% else %>
                <li><%= link_to "about", about_path, class: 'nav-link text-dark' %></li>
                <li><%= link_to 'sign up', new_member_registration_path, class: 'nav-link text-dark' %></li>
                <li><%= link_to "Login", new_member_session_path, class: 'nav-link text-dark' %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="main">
      <%= yield %>
    </main>

    <footer class="footer">
      <nav class="site-menu">
        <ul>
        <%# ユーザーログイン後のフッター%>
        <% if member_signed_in? %>
          <li><%= link_to 'ホーム', videos_path, class: 'nav-link text-dark' %></li>
          <li><%= link_to 'マイページ', user_path(current_member.id), class: 'nav-link text-dark' %></li>
          <li><%= link_to '投稿フォーム', new_video_path, class: 'nav-link text-dark' %></li>
          <li><%= link_to 'ログアウト', destroy_member_session_path, method: :delete, class: 'nav-link text-dark' %></li>
        <%# 管理者ログイン後のフッター　%>
        <% elsif admin_signed_in? %>
          <li><%= link_to '会員一覧', admin_customers_path, class: 'nav-link text-dark' %></li>
          <li><%= link_to 'ジャンル一覧', admin_genres_path, class: 'nav-link text-dark' %></li>
          <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %></li>
        <%# ログイン前のフッター(ユーザー、管理者共通)　%>
        <% else %>
          <li><%= link_to "アバウト", about_path, class: 'nav-link text-dark' %></li>
          <li><%= link_to '新規登録', new_member_registration_path, class: 'nav-link text-dark' %></li>
          <li><%= link_to "ログイン", new_member_session_path, class: 'nav-link text-dark' %></li>
          <li><%= link_to "管理者 Log-in", new_admin_session_path, class: 'nav-link text-dark' %></li>
        <% end %>
        </ul>
      </nav>
      <%# 検索機能 %>
      <%= render 'member/searches/search', members: @records %>
    </footer>

  </body>
</html>